### ISSUE TITLE
[Feature request]可否支持图片和卡片

### ISSUE THREAD

**Issue by ABKQPO** [Cvandia/nonebot-plugin-fakemsg#1]

**Comment by Cvandia** [comment]
![Screenshot_20230829_134724.jpg](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/106718176/a25f91f7-8735-4052-a929-7658b3d0eb27)

是支持图片的，你说的卡片是指？

**Comment by ABKQPO** [comment]
类似于转发到B站视频卡片，网易云卡片等等，能否进行分段发送然后合并成一条合并消息，这样发送图片在生成很多条合并消息时是如何判断的

**Comment by ABKQPO** [comment]
当一条消息内存在另一个'说'字时，后面的字不会被识别

**Comment by Cvandia** [comment]
> 类似于转发到B站视频卡片，网易云卡片等等，能否进行分段发送然后合并成一条合并消息，这样发送图片在生成很多条合并消息时是如何判断的

可以，你可以利用`on_message`和`on_command`的事件响应器，利用`command`发送“开始伪造”的指令后，开启伪造消息的状态。利用`rule`和`on_message`判断是否处在伪造消息状态。如果是，则读取每条消息储存，如果不是则跳过。最后可以尝试通过“伪造结束”的指令发送储存的消息，并清除伪造消息的状态

**Comment by ABKQPO** [comment]
可以，能否伪造发送时间？

**Comment by ABKQPO** [comment]
群内合并消息可以携带群头衔和群机器人图标，这个如何设置

**Comment by Cvandia** [comment]
> 当一条消息内存在另一个'说'字时，后面的字不会被识别

知道原因了，下版本改成`split('说', 0)`

**Comment by Cvandia** [comment]
> 可以，能否伪造发送时间？

`go-cqhttp`的合并转发好像没有自定义时间的功能

**Comment by ABKQPO** [comment]
卡片发送和表情包这种是否应该识别先识别发送者然后再识别消息最后合并？

**Comment by Cvandia** [comment]
> 卡片发送和表情包这种是否应该识别先识别发送者然后再识别消息最后合并？

都可以，看你逻辑啦

**Comment by ABKQPO** [comment]
建议匹配第一条发送者，第二条匹配发送内容，这样可以解决命令冲突的问题

**Comment by Cvandia** [comment]
> 建议匹配第一条发送者，第二条匹配发送内容，这样可以解决命令冲突的问题

欸嘿，我摆烂 :P

**Comment by IllusiveBull** [comment]
> > 可以，能否伪造发送时间？
> 
> `go-cqhttp`的合并转发好像没有自定义时间的功能

有的，在data里加time就可以
```
{
"type": "node",
"data": {
    "name": "",
    "uin": "",
    "time":time.time(),
    "content": ""
}
}```

**Comment by Cvandia** [comment]
> > > 可以，能否伪造发送时间？
> > 
> > `go-cqhttp`的合并转发好像没有自定义时间的功能
> 
> 有的，在data里加time就可以
> ```
> {
> "type": "node",
> "data": {
>     "name": "",
>     "uin": "",
>     "time":time.time(),
>     "content": ""
> }
> }```

可以的，但我这插件应该用不上这么详细吧（

**Comment by Q1351998764** [comment]
> > > > 可以，能否伪造发送时间？
> > > 
> > > 
> > > `go-cqhttp`的合并转发好像没有自定义时间的功能
> > 
> > 
> > 有的，在data里加time就可以
> > ```
> > {
> > "type": "node",
> > "data": {
> >     "name": "",
> >     "uin": "",
> >     "time":time.time(),
> >     "content": ""
> > }
> > }```
> > ```
> 
> 可以的，但我这插件应该用不上这么详细吧（

竟然还真能伪造发送时间，nor酱加油！
![9~ VL$A3$I}2RL(GUP5NUZ7](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/57926506/a944c2a8-a9ca-43f8-ada4-9715f5d5ca4e)
