### ISSUE TITLE
[Help]fakepic中文乱码

### ISSUE THREAD

**Issue by greenhandzdl** [Cvandia/nonebot-plugin-fakemsg#14]
![Screenshot_2024-11-14-19-02-13-298_com.tencent.mobileqq.jpg](https://github.com/user-attachments/assets/933ca8e3-816b-4532-91f7-7250676caff8)
怎么解决？

**Comment by Cvandia** [comment]
根据上传的截图信息来看，似乎不是使用了本仓库的插件， 而是[nonebot-plugin-memes](https://github.com/noneplugin/nonebot-plugin-memes)中的`我朋友说 xxxx`类似的功能效果

**Comment by greenhandzdl** [comment]
![IMG_20241114_191845.jpg](https://github.com/user-attachments/assets/e91a8eb4-d7de-48d4-9b53-ed2d718f6bfe)

是fakemsg这个插件，我确信

**Comment by Cvandia** [comment]
@greenhandzdl 对应在[nonebot-plugin-fakepic](https://github.com/lm175/nonebot-plugin-fakepic)下提issue，当然也欢迎使用本插件

**Comment by greenhandzdl** [comment]
抱歉，打扰了

**Comment by greenhandzdl** [comment]
话说这个可以和那个共存吗？我先去那边开个issues

**Comment by Cvandia** [comment]
> 话说这个可以和那个共存吗？我先去那边开个issues

可能会存在本插件优先级高，阻断了`fakepic`插件的响应
