### ISSUE TITLE
使用@别人说，供群内娱乐

### ISSUE THREAD

**Issue by YingLing3** [Cvandia/nonebot-plugin-fakemsg#2]
伪造消息还得一个一个点开个人资料，再复制QQ号，过于繁琐，建议添加艾特伪造

**Comment by Cvandia** [comment]
> 伪造消息还得一个一个点开个人资料，再复制QQ号，过于繁琐，建议添加艾特伪造

可以，后续加

**Comment by Cvandia** [comment]
> 伪造消息还得一个一个点开个人资料，再复制QQ号，过于繁琐，建议添加艾特伪造
![IMG_20230830_144242.png](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/106718176/4d88d2c0-52de-4621-a188-8befe3c97ca7)
![IMG_20230830_144227.jpg](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/106718176/05183d86-833d-4076-862f-9587f93746ff)




效果来了，后面再更
