### ISSUE TITLE
[SUGGEST]建议加一个自定义时间

### ISSUE THREAD

**Issue by huanyan434** [Cvandia/nonebot-plugin-fakemsg#4]

**Comment by Cvandia** [comment]
可以，但不实用。如果想实现，请参考`go-cqhttp`文档的CQ码部分[合并转发](https://docs.go-cqhttp.org/cqcode/#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E6%B6%88%E6%81%AF%E8%8A%82%E7%82%B9)

**Comment by huanyan434** [comment]
文档中没有提到发送消息时间？

**Comment by Cvandia** [comment]
> 文档中没有提到发送消息时间？

参考[#1](https://github.com/Cvandia/nonebot-plugin-fakemsg/issues/1)提议的[回复](https://github.com/Cvandia/nonebot-plugin-fakemsg/issues/1#issuecomment-1700438168)
