### ISSUE TITLE
伪造信息里显示的是群友昵称就更好了。

### ISSUE THREAD

**Issue by saferabbit** [Cvandia/nonebot-plugin-fakemsg#5]
GitHub里的代码会报错

**Comment by Cvandia** [comment]
- gh的代码还没经过测试(
- 群友昵称可以吧`get_stranger_info`替换为`get_group_member_info`

**Comment by saferabbit** [comment]
> * gh的代码还没经过测试(
> * 群友昵称可以吧`get_stranger_info`替换为`get_group_member_info`

直接替换会提示找不到group，找不到群聊
报错信息：
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(data=None, echo='3', message='群聊不存在', msg='GROUP_NOT_FOUND', retcode=100, status='failed', wording='群聊不存在')

**Comment by Cvandia** [comment]
![image](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/106718176/f18d469b-9560-4134-aab0-28a02e2ae63d)
c请确定参数是否完整

**Comment by Cvandia** [comment]
![image](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/106718176/ae0e91d7-500a-425a-9914-e23a362357a9)
并且更改nickname为card

**Comment by Cvandia** [comment]
类似以下的代码
``` python
if isinstance(event, GroupMessageEvent):
        name = await bot.get_group_member_info(group_id=event.group_id, user_id=int(qq))
        name = name["card"] if name["card"] else name["nickname"]
```

**Comment by saferabbit** [comment]
> 类似以下的代码
> 
> ```python
> if isinstance(event, GroupMessageEvent):
>         name = await bot.get_group_member_info(group_id=event.group_id, user_id=int(qq))
>         name = name["card"] if name["card"] else name["nickname"]
> ```

感谢回答，我没留意到要改参数，按这方法成功了。
