### ISSUE TITLE
[BUG]伪造消息失败

### ISSUE THREAD

**Issue by QSlotus** [Cvandia/nonebot-plugin-fakemsg#8]
**描述bug**
伪造消息失败

**怎么出现的**
1. 在bot.py中成功加载插件
2. 在群内输入伪造消息指令
3. 伪造失败，后台报错
……

**异常情况**
日志如下
```
02-16 17:16:11 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_fakemsg, lineno=60) failed.
Traceback (most recent call last):
  File "/data/nb/bot.py", line 29, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/drivers/fastapi.py", line 185, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 817, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_fakemsg/__init__.py", line 76, in _
    name = await bot.get_stranger_info(user_id=qq)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/adapter/bot.py", line 122, in call_api
    raise exception
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/adapter/bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/adapters/onebot/v11/adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "/usr/local/lib/python3.10/dist-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=404, data=None, echo='3')
```

**屏幕截图**
无

**版本情况**
python: 3.10.12
nb-cli: 1.3.0
pip: 24.0
……

**额外的说明**
无

**Comment by Cvandia** [comment]
适配器使用的是？

**Comment by Cvandia** [comment]
好的，可能`get_stranger_info`API失效了

**Comment by Cvandia** [comment]
> 好的，可能`get_stranger_info`API失效了

尝试使用`get_group_member_info`来获取群成员信息，但确保伪造消息成员在本群中

**Comment by VAHua** [comment]
消息发送成功，但是没有伪造
![image](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/129832780/c26e4e2b-9d77-4f74-9f08-2ef993c4ab02)
![image](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/129832780/e095a786-fb1d-4919-9534-aac988e28531)
![image](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/129832780/60ebc1e7-68db-48e4-8ac9-3fe22fbd8b6d)


> > 好的，可能`get_stranger_info`API失效了
> 
> 尝试使用`get_group_member_info`来获取群成员信息，但确保伪造消息成员在本群中

**Comment by Cvandia** [comment]
@VAHua 具体的onebot实现端是什么，我记得Lagrange还是llonebot的`get_stranger_info`的API实现不了具体功能，改成`get_group_member_info`尝试

**Comment by VAHua** [comment]
> @VAHua 具体的onebot实现端是什么，我记得Lagrange还是llonebot的`get_stranger_info`的API实现不了具体功能，改成`get_group_member_info`尝试

被你说中了大佬，我用的就是llonebot，我去改成get_group_member_info试试

**Comment by VAHua** [comment]
> @VAHua 具体的onebot实现端是什么，我记得Lagrange还是llonebot的`get_stranger_info`的API实现不了具体功能，改成`get_group_member_info`尝试

经过测试，还是不行
![image](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/129832780/e19b03f0-368b-43bb-b0b9-d9bc16aa39e8)
![image](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/129832780/4b171c46-c45c-4af9-8ced-eb5cfddddc35)
![image](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/129832780/7c7964f9-f3d3-4394-a066-cc930f086744)

**Comment by Cvandia** [comment]
@VAHua 伪造消息的人在群里吗？

**Comment by VAHua** [comment]
> @VAHua 伪造消息的人在群里吗？

是的，都在，只是不是好友

**Comment by Cvandia** [comment]
> > @VAHua 伪造消息的人在群里吗？
> 
> 是的，都在，只是不是好友

实现端是哪个？gocq，llbot还是Lagrange

**Comment by VAHua** [comment]
> > > @VAHua 伪造消息的人在群里吗？
> > 
> > 
> > 是的，都在，只是不是好友
> 
> 实现端是哪个？gocq，llbot还是Lagrange

llonebot反向连接nonebot2

**Comment by Cvandia** [comment]
> > @VAHua 伪造消息的人在群里吗？
> 
> 是的，都在，只是不是好友

![Screenshot_20240319_111201.jpg](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/106718176/b7d2886b-a0ad-4612-a4d8-71cc155840e3)

确认`get_group_member_info`函数参数

**Comment by VAHua** [comment]
> > > @VAHua 伪造消息的人在群里吗？
> > 
> > 
> > 是的，都在，只是不是好友
> 
> ![Screenshot_20240319_111201.jpg](https://private-user-images.githubusercontent.com/106718176/313901581-b7d2886b-a0ad-4612-a4d8-71cc155840e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTgyOTYsIm5iZiI6MTcxMDgxNzk5NiwicGF0aCI6Ii8xMDY3MTgxNzYvMzEzOTAxNTgxLWI3ZDI4ODZiLWEwYWQtNDYxMi1hNGQ4LTcxY2MxNTU4NDBlMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMzEzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjQ2Njc2NDlhYjA1OGM4NDY2ZWY3Y2VmNzE4NjY3MDU0Y2JkYTMwMTE3NTU1NWQ2NTNiYzM3N2UwYmY0MjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R64KBtbg1n3fCxOXb-LLeArF2Q-0zQDiJM5sikCFqWw)
> 
> 确认`get_group_member_info`函数参数

确认无误
![image](https://github.com/Cvandia/nonebot-plugin-fakemsg/assets/129832780/bec68bc8-cde2-48e9-9914-1fc8604eee9a)

**Comment by VAHua** [comment]
> > > @VAHua 伪造消息的人在群里吗？
> > 
> > 
> > 是的，都在，只是不是好友
> 
> ![Screenshot_20240319_111201.jpg](https://private-user-images.githubusercontent.com/106718176/313901581-b7d2886b-a0ad-4612-a4d8-71cc155840e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTg5MjksIm5iZiI6MTcxMDgxODYyOSwicGF0aCI6Ii8xMDY3MTgxNzYvMzEzOTAxNTgxLWI3ZDI4ODZiLWEwYWQtNDYxMi1hNGQ4LTcxY2MxNTU4NDBlMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMzIzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWZkMmM0NmUxYTVmZWNkZGVmMTFlZjkxMjkwZGUyZTczYjdkZjNmMmMyNjBmNDE2ZTg2ZTAyMGVhMzg3ZGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5kf-uE9CC_34vakNnzfaHkLJpRXyX1pPHizTI0Ve_G8)
> 
> 确认`get_group_member_info`函数参数

已找到错误，llonebot的问题，麻烦大佬了！

```
2024/3/19 11:22:15 monika(2767629104): ws 消息上报 ws://127.0.0.1:8080/onebot/v11/ws {"status":"ok","retcode":0,"data":{"message_id":-2147454976},"message":"","wording":"","echo":"23"} 

2024/3/19 11:22:15 monika(2767629104): 收到反向Websocket消息 {"action":"get_group_member_info","params":{"user_id":2237905521},"echo":"24"} 

2024/3/19 11:22:15 monika(2767629104): 发生错误 {} 

2024/3/19 11:22:15 monika(2767629104): ws 消息上报 ws://127.0.0.1:8080/onebot/v11/ws {"status":"failed","retcode":1200,"data":null,"message":"TypeError: Cannot read properties of undefined (reading 'toString')\n    at GetGroupMemberInfo._handle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6812:58)\n    at GetGroupMemberInfo.websocketHandle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6697:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ReverseWebsocket.onmessage (d:\\Program Files\\Tencen...","wording":"TypeError: Cannot read properties of undefined (reading 'toString')\n    at GetGroupMemberInfo._handle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6812:58)\n    at GetGroupMemberInfo.websocketHandle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6697:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ReverseWebsocket.onmessage (d:\\Program Files\\Tencen...","echo":"24"} 

2024/3/19 11:22:15 monika(2767629104): 收到反向Websocket消息 {"action":"get_group_member_info","params":{"user_id":743703324},"echo":"25"} 

2024/3/19 11:22:15 monika(2767629104): ws 消息上报 ws://127.0.0.1:8080/onebot/v11/ws {"status":"failed","retcode":1200,"data":null,"message":"TypeError: Cannot read properties of undefined (reading 'toString')\n    at GetGroupMemberInfo._handle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6812:58)\n    at GetGroupMemberInfo.websocketHandle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6697:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ReverseWebsocket.onmessage (d:\\Program Files\\Tencen...","wording":"TypeError: Cannot read properties of undefined (reading 'toString')\n    at GetGroupMemberInfo._handle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6812:58)\n    at GetGroupMemberInfo.websocketHandle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6697:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ReverseWebsocket.onmessage (d:\\Program Files\\Tencen...","echo":"25"} 

2024/3/19 11:22:15 monika(2767629104): 发生错误 {} 
```

**Comment by syagina** [comment]
> > > > @VAHua 伪造消息的人在群里吗？
> > > 
> > > 
> > > 是的，都在，只是不是好友
> > 
> > ![Screenshot_20240319_111201.jpg](https://private-user-images.githubusercontent.com/106718176/313901581-b7d2886b-a0ad-4612-a4d8-71cc155840e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTg5MjksIm5iZiI6MTcxMDgxODYyOSwicGF0aCI6Ii8xMDY3MTgxNzYvMzEzOTAxNTgxLWI3ZDI4ODZiLWEwYWQtNDYxMi1hNGQ4LTcxY2MxNTU4NDBlMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMzIzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWZkMmM0NmUxYTVmZWNkZGVmMTFlZjkxMjkwZGUyZTczYjdkZjNmMmMyNjBmNDE2ZTg2ZTAyMGVhMzg3ZGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5kf-uE9CC_34vakNnzfaHkLJpRXyX1pPHizTI0Ve_G8)
> > 
> > 确认`get_group_member_info`函数参数
> 
> 已找到错误，llonebot的问题，麻烦大佬了！
> 
> ```
> 2024/3/19 11:22:15 monika(2767629104): ws 消息上报 ws://127.0.0.1:8080/onebot/v11/ws {"status":"ok","retcode":0,"data":{"message_id":-2147454976},"message":"","wording":"","echo":"23"} 
> 
> 2024/3/19 11:22:15 monika(2767629104): 收到反向Websocket消息 {"action":"get_group_member_info","params":{"user_id":2237905521},"echo":"24"} 
> 
> 2024/3/19 11:22:15 monika(2767629104): 发生错误 {} 
> 
> 2024/3/19 11:22:15 monika(2767629104): ws 消息上报 ws://127.0.0.1:8080/onebot/v11/ws {"status":"failed","retcode":1200,"data":null,"message":"TypeError: Cannot read properties of undefined (reading 'toString')\n    at GetGroupMemberInfo._handle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6812:58)\n    at GetGroupMemberInfo.websocketHandle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6697:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ReverseWebsocket.onmessage (d:\\Program Files\\Tencen...","wording":"TypeError: Cannot read properties of undefined (reading 'toString')\n    at GetGroupMemberInfo._handle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6812:58)\n    at GetGroupMemberInfo.websocketHandle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6697:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ReverseWebsocket.onmessage (d:\\Program Files\\Tencen...","echo":"24"} 
> 
> 2024/3/19 11:22:15 monika(2767629104): 收到反向Websocket消息 {"action":"get_group_member_info","params":{"user_id":743703324},"echo":"25"} 
> 
> 2024/3/19 11:22:15 monika(2767629104): ws 消息上报 ws://127.0.0.1:8080/onebot/v11/ws {"status":"failed","retcode":1200,"data":null,"message":"TypeError: Cannot read properties of undefined (reading 'toString')\n    at GetGroupMemberInfo._handle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6812:58)\n    at GetGroupMemberInfo.websocketHandle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6697:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ReverseWebsocket.onmessage (d:\\Program Files\\Tencen...","wording":"TypeError: Cannot read properties of undefined (reading 'toString')\n    at GetGroupMemberInfo._handle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6812:58)\n    at GetGroupMemberInfo.websocketHandle (d:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:6697:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ReverseWebsocket.onmessage (d:\\Program Files\\Tencen...","echo":"25"} 
> 
> 2024/3/19 11:22:15 monika(2767629104): 发生错误 {} 
> ```

最终解决方法是？
